CREATE TABLE IF NOT EXISTS "util"."pending_embedding_jobs" (
    "id" bigint NOT NULL,
    "schema_name" "text" NOT NULL,
    "table_name" "text" NOT NULL,
    "record_id" "text" NOT NULL,
    "record_version" "text" NOT NULL,
    "content_function" "text" NOT NULL,
    "embedding_column" "text" NOT NULL,
    "edge_function" "text" NOT NULL,
    "message" "jsonb" NOT NULL,
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "queue_msg_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "enqueued_at" timestamp with time zone,
    CONSTRAINT "pending_embedding_jobs_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'enqueued'::"text", 'discarded'::"text"])))
);

ALTER TABLE "util"."pending_embedding_jobs" OWNER TO "postgres";

COMMENT ON TABLE "util"."pending_embedding_jobs" IS 'Stores embedding jobs held by deferred or paused queue policies until controlled backfill.';

ALTER TABLE "util"."pending_embedding_jobs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "util"."pending_embedding_jobs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "util"."pending_embedding_jobs"
    ADD CONSTRAINT "pending_embedding_jobs_pkey" PRIMARY KEY ("id");
