CREATE TABLE IF NOT EXISTS "util"."embedding_queue_policy" (
    "id" bigint NOT NULL,
    "scope_schema" "text" DEFAULT '*'::"text" NOT NULL,
    "scope_table" "text" DEFAULT '*'::"text" NOT NULL,
    "scope_edge_function" "text" DEFAULT '*'::"text" NOT NULL,
    "scope_embedding_column" "text" DEFAULT '*'::"text" NOT NULL,
    "mode" "text" DEFAULT 'normal'::"text" NOT NULL,
    "max_in_flight" integer DEFAULT 10 NOT NULL,
    "max_read_count" integer DEFAULT 20 NOT NULL,
    "retry_backoff_seconds" integer DEFAULT 300 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "embedding_queue_policy_mode_check" CHECK (("mode" = ANY (ARRAY['normal'::"text", 'deferred'::"text", 'paused'::"text"]))),
    CONSTRAINT "embedding_queue_policy_positive_limits_check" CHECK ((("max_in_flight" > 0) AND ("max_read_count" > 0) AND ("retry_backoff_seconds" > 0))),
    CONSTRAINT "embedding_queue_policy_scope_not_empty_check" CHECK ((("scope_schema" <> ''::"text") AND ("scope_table" <> ''::"text") AND ("scope_edge_function" <> ''::"text") AND ("scope_embedding_column" <> ''::"text")))
);

ALTER TABLE "util"."embedding_queue_policy" OWNER TO "postgres";

COMMENT ON TABLE "util"."embedding_queue_policy" IS 'Controls embedding job queue behavior by schema/table/edge function/embedding column scope.';

ALTER TABLE "util"."embedding_queue_policy" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "util"."embedding_queue_policy_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "util"."embedding_queue_policy"
    ADD CONSTRAINT "embedding_queue_policy_pkey" PRIMARY KEY ("id");
