CREATE OR REPLACE VIEW "public"."worker_domain_traceability_cutoffs" WITH ("security_invoker"='true') AS
 SELECT "domain_source",
    "required_worker_column",
    "cutover_at",
    "traceability_required",
    "contract_note"
   FROM ( VALUES ('lca_results'::"text",'worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'new LCA result artifacts must be linked to the worker_jobs task that produced them'::"text"), ('lca_result_cache'::"text",'worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'new LCA result-cache rows must be linked to their backing worker_jobs task'::"text"), ('lca_latest_all_unit_results'::"text",'worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'new latest all-unit projections must be linked to the worker_jobs task that produced them'::"text"), ('lca_factorization_registry'::"text",'prepared_worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'prepared factorization rows must be linked to the worker_jobs task that prepared them'::"text"), ('lca_package_artifacts'::"text",'worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'new package artifact metadata must be linked to the worker_jobs task that produced it'::"text"), ('lca_package_export_items'::"text",'worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'new package export/import item state must be linked to the worker_jobs task that produced it'::"text"), ('lca_package_request_cache'::"text",'worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'new package request-cache rows must be linked to their backing worker_jobs task'::"text"), ('dataset_review_submit_requests'::"text",'submit_worker_job_id,gate_worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'new review-submit coordinator rows must be linked to root submit and gate worker_jobs tasks once they enter the worker flow'::"text"), ('dataset_review_submit_gate_runs'::"text",'worker_job_id'::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,true,'new review-submit gate reports must be linked to their gate worker_jobs task'::"text"), ('lca_network_snapshots'::"text",NULL::"text",'2026-06-03 13:35:00+00'::timestamp with time zone,false,'snapshot rows are domain cache identity and are currently traced through downstream worker-linked result/cache/latest/factorization rows'::"text")) "cutoffs"("domain_source", "required_worker_column", "cutover_at", "traceability_required", "contract_note");

ALTER VIEW "public"."worker_domain_traceability_cutoffs" OWNER TO "postgres";
