CREATE TABLE IF NOT EXISTS "util"."embedding_job_failures" (
    "id" bigint NOT NULL,
    "queue_name" "text" DEFAULT 'embedding_jobs'::"text" NOT NULL,
    "msg_id" bigint,
    "read_count" integer,
    "reason" "text" NOT NULL,
    "message" "jsonb" NOT NULL,
    "failed_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "util"."embedding_job_failures" OWNER TO "postgres";

COMMENT ON TABLE "util"."embedding_job_failures" IS 'Dead-letter record for embedding jobs removed from pgmq after exceeding retry policy.';

ALTER TABLE "util"."embedding_job_failures" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "util"."embedding_job_failures_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "util"."embedding_job_failures"
    ADD CONSTRAINT "embedding_job_failures_pkey" PRIMARY KEY ("id");
