create table if not exists util.embedding_queue_policy (
  id bigint generated by default as identity primary key,
  scope_schema text not null default '*',
  scope_table text not null default '*',
  scope_edge_function text not null default '*',
  scope_embedding_column text not null default '*',
  mode text not null default 'normal',
  max_in_flight integer not null default 10,
  max_read_count integer not null default 20,
  retry_backoff_seconds integer not null default 300,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint embedding_queue_policy_mode_check
    check (mode in ('normal', 'deferred', 'paused')),
  constraint embedding_queue_policy_scope_not_empty_check
    check (
      scope_schema <> ''
      and scope_table <> ''
      and scope_edge_function <> ''
      and scope_embedding_column <> ''
    ),
  constraint embedding_queue_policy_positive_limits_check
    check (
      max_in_flight > 0
      and max_read_count > 0
      and retry_backoff_seconds > 0
    )
);

create unique index if not exists embedding_queue_policy_scope_key
  on util.embedding_queue_policy (
    scope_schema,
    scope_table,
    scope_edge_function,
    scope_embedding_column
  );

create table if not exists util.pending_embedding_jobs (
  id bigint generated by default as identity primary key,
  schema_name text not null,
  table_name text not null,
  record_id text not null,
  record_version text not null,
  content_function text not null,
  embedding_column text not null,
  edge_function text not null,
  message jsonb not null,
  status text not null default 'pending',
  queue_msg_id bigint,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  enqueued_at timestamp with time zone,
  constraint pending_embedding_jobs_status_check
    check (status in ('pending', 'enqueued', 'discarded'))
);

create unique index if not exists pending_embedding_jobs_pending_scope_key
  on util.pending_embedding_jobs (
    schema_name,
    table_name,
    record_id,
    record_version,
    embedding_column,
    edge_function
  )
  where status = 'pending';

create table if not exists util.embedding_job_failures (
  id bigint generated by default as identity primary key,
  queue_name text not null default 'embedding_jobs',
  msg_id bigint,
  read_count integer,
  reason text not null,
  message jsonb not null,
  failed_at timestamp with time zone not null default now()
);

create index if not exists embedding_job_failures_failed_at_idx
  on util.embedding_job_failures (failed_at desc);

insert into util.embedding_queue_policy (
  scope_schema,
  scope_table,
  scope_edge_function,
  scope_embedding_column,
  mode,
  max_in_flight,
  max_read_count,
  retry_backoff_seconds
)
values
  ('*', '*', '*', '*', 'normal', 10, 20, 300),
  ('public', 'flows', 'embedding_ft', 'embedding_ft', 'normal', 2, 20, 300)
on conflict (
  scope_schema,
  scope_table,
  scope_edge_function,
  scope_embedding_column
) do update
set
  mode = excluded.mode,
  max_in_flight = excluded.max_in_flight,
  max_read_count = excluded.max_read_count,
  retry_backoff_seconds = excluded.retry_backoff_seconds,
  updated_at = now();

create or replace function util.embedding_queue_policy_for(
  p_schema_name text,
  p_table_name text,
  p_edge_function text,
  p_embedding_column text
)
returns table (
  mode text,
  max_in_flight integer,
  max_read_count integer,
  retry_backoff_seconds integer
)
language sql
stable
set search_path to ''
as $$
  select
    p.mode,
    p.max_in_flight,
    p.max_read_count,
    p.retry_backoff_seconds
  from util.embedding_queue_policy p
  where p.scope_schema in ('*', coalesce(p_schema_name, ''))
    and p.scope_table in ('*', coalesce(p_table_name, ''))
    and p.scope_edge_function in ('*', coalesce(p_edge_function, 'embedding'))
    and p.scope_embedding_column in ('*', coalesce(p_embedding_column, ''))
  order by
    (
      (p.scope_schema <> '*')::integer
      + (p.scope_table <> '*')::integer
      + (p.scope_edge_function <> '*')::integer
      + (p.scope_embedding_column <> '*')::integer
    ) desc,
    p.updated_at desc,
    p.id desc
  limit 1
$$;

alter function util.embedding_queue_policy_for(text, text, text, text) owner to postgres;

create or replace function util.process_embeddings(
  batch_size integer default 3,
  max_requests integer default 3,
  timeout_milliseconds integer default ((5 * 60) * 1000)
) returns void
language plpgsql
set search_path to ''
as $$
declare
  job_batches jsonb[];
  batch jsonb;
  edge_fn text;
  timeout_seconds integer;
begin
  if batch_size <= 0 or max_requests <= 0 then
    return;
  end if;

  if not pg_try_advisory_xact_lock(hashtext('util.process_embeddings')) then
    return;
  end if;

  timeout_seconds := greatest(1, ceiling(timeout_milliseconds / 1000.0)::integer);

  with expired_jobs as (
    select
      q.msg_id,
      q.message,
      q.read_ct,
      p.max_read_count
    from pgmq.q_embedding_jobs q
    cross join lateral util.embedding_queue_policy_for(
      coalesce(q.message->>'schema', ''),
      coalesce(q.message->>'table', ''),
      coalesce(q.message->>'edgeFunction', 'embedding'),
      coalesce(q.message->>'embeddingColumn', '')
    ) p
    where q.vt <= clock_timestamp()
      and q.read_ct >= p.max_read_count
    order by q.msg_id
    limit greatest(batch_size * max_requests, 100)
  ),
  recorded_failures as (
    insert into util.embedding_job_failures (
      queue_name,
      msg_id,
      read_count,
      reason,
      message
    )
    select
      'embedding_jobs',
      e.msg_id,
      e.read_ct,
      format('read_ct reached retry cap %s', e.max_read_count),
      e.message
    from expired_jobs e
    returning msg_id
  )
  delete from pgmq.q_embedding_jobs q
  using recorded_failures f
  where q.msg_id = f.msg_id;

  with visible_jobs as (
    select
      q.msg_id,
      q.message,
      coalesce(q.message->>'schema', '') as schema_name,
      coalesce(q.message->>'table', '') as table_name,
      coalesce(q.message->>'edgeFunction', 'embedding') as edge_function,
      coalesce(q.message->>'embeddingColumn', '') as embedding_column
    from pgmq.q_embedding_jobs q
    where q.vt <= clock_timestamp()
  ),
  scoped_jobs as (
    select
      v.*,
      p.max_in_flight,
      active.active_count,
      row_number() over (
        partition by
          v.schema_name,
          v.table_name,
          v.edge_function,
          v.embedding_column
        order by v.msg_id
      ) as scope_position
    from visible_jobs v
    cross join lateral util.embedding_queue_policy_for(
      v.schema_name,
      v.table_name,
      v.edge_function,
      v.embedding_column
    ) p
    cross join lateral (
      select count(*)::integer as active_count
      from pgmq.q_embedding_jobs active
      where active.vt > clock_timestamp()
        and coalesce(active.message->>'schema', '') = v.schema_name
        and coalesce(active.message->>'table', '') = v.table_name
        and coalesce(active.message->>'edgeFunction', 'embedding') = v.edge_function
        and coalesce(active.message->>'embeddingColumn', '') = v.embedding_column
    ) active
    where p.mode = 'normal'
  ),
  selected_jobs as (
    select *
    from scoped_jobs
    where active_count < max_in_flight
      and scope_position <= (max_in_flight - active_count)
    order by msg_id
    limit (batch_size * max_requests)
  ),
  claimed_jobs as (
    update pgmq.q_embedding_jobs q
    set
      vt = clock_timestamp() + timeout_seconds * interval '1 second',
      read_ct = q.read_ct + 1
    from selected_jobs s
    where q.msg_id = s.msg_id
    returning
      q.msg_id,
      q.message || jsonb_build_object('jobId', q.msg_id) as job_info,
      coalesce(q.message->>'edgeFunction', 'embedding') as edge_function
  ),
  numbered_jobs as (
    select
      c.msg_id,
      c.job_info,
      c.edge_function,
      ((row_number() over (
        partition by c.edge_function
        order by c.msg_id
      ) - 1) / batch_size) as batch_num
    from claimed_jobs c
  ),
  batched_jobs as (
    select
      jsonb_agg(job_info order by msg_id) as batch_array,
      edge_function,
      batch_num
    from numbered_jobs
    group by edge_function, batch_num
    order by edge_function, batch_num
  )
  select array_agg(batch_array)
  from batched_jobs
  into job_batches;

  if job_batches is null then
    return;
  end if;

  foreach batch in array job_batches loop
    edge_fn := batch->0->>'edgeFunction';

    perform util.invoke_edge_function(
      name => edge_fn,
      body => batch,
      timeout_milliseconds => timeout_milliseconds
    );
  end loop;
end;
$$;

alter function util.process_embeddings(integer, integer, integer) owner to postgres;

create or replace function util.queue_embeddings() returns trigger
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_content_function text = TG_ARGV[0];
  v_embedding_column text = TG_ARGV[1];
  v_edge_function text := coalesce(TG_ARGV[2], 'embedding');
  queue_mode text;
  v_message jsonb;
begin
  v_message := jsonb_build_object(
    'id', NEW.id,
    'version', NEW.version,
    'schema', TG_TABLE_SCHEMA,
    'table', TG_TABLE_NAME,
    'contentFunction', v_content_function,
    'embeddingColumn', v_embedding_column,
    'edgeFunction', v_edge_function
  );

  select p.mode
    into queue_mode
  from util.embedding_queue_policy_for(
    TG_TABLE_SCHEMA,
    TG_TABLE_NAME,
    v_edge_function,
    v_embedding_column
  ) p;

  if queue_mode in ('deferred', 'paused') then
    insert into util.pending_embedding_jobs (
      schema_name,
      table_name,
      record_id,
      record_version,
      content_function,
      embedding_column,
      edge_function,
      message
    )
    values (
      TG_TABLE_SCHEMA,
      TG_TABLE_NAME,
      NEW.id::text,
      NEW.version::text,
      v_content_function,
      v_embedding_column,
      v_edge_function,
      v_message
    )
    on conflict (
      schema_name,
      table_name,
      record_id,
      record_version,
      embedding_column,
      edge_function
    )
    where status = 'pending'
    do update
    set
      content_function = excluded.content_function,
      message = excluded.message,
      updated_at = now();

    return NEW;
  end if;

  perform pgmq.send(
    queue_name => 'embedding_jobs',
    msg => v_message
  );

  return NEW;
end;
$$;

alter function util.queue_embeddings() owner to postgres;

create or replace function util.enqueue_pending_embeddings(
  p_limit integer default 100,
  p_schema_name text default null,
  p_table_name text default null,
  p_edge_function text default null,
  p_embedding_column text default null
) returns integer
language plpgsql
security definer
set search_path to ''
as $$
declare
  pending_job record;
  sent_count integer := 0;
  sent_msg_id bigint;
begin
  if p_limit <= 0 then
    return 0;
  end if;

  if not pg_try_advisory_xact_lock(hashtext('util.enqueue_pending_embeddings')) then
    return 0;
  end if;

  for pending_job in
    select pending.*
    from util.pending_embedding_jobs pending
    cross join lateral util.embedding_queue_policy_for(
      pending.schema_name,
      pending.table_name,
      pending.edge_function,
      pending.embedding_column
    ) p
    where pending.status = 'pending'
      and p.mode <> 'paused'
      and (p_schema_name is null or pending.schema_name = p_schema_name)
      and (p_table_name is null or pending.table_name = p_table_name)
      and (p_edge_function is null or pending.edge_function = p_edge_function)
      and (p_embedding_column is null or pending.embedding_column = p_embedding_column)
    order by pending.created_at, pending.id
    limit p_limit
    for update skip locked
  loop
    select pgmq.send(
      queue_name => 'embedding_jobs',
      msg => pending_job.message
    )
    into sent_msg_id;

    update util.pending_embedding_jobs
    set
      status = 'enqueued',
      queue_msg_id = sent_msg_id,
      enqueued_at = now(),
      updated_at = now()
    where id = pending_job.id;

    sent_count := sent_count + 1;
  end loop;

  return sent_count;
end;
$$;

alter function util.enqueue_pending_embeddings(
  integer,
  text,
  text,
  text,
  text
) owner to postgres;

comment on table util.embedding_queue_policy is
  'Controls embedding job queue behavior by schema/table/edge function/embedding column scope.';

comment on table util.pending_embedding_jobs is
  'Stores embedding jobs held by deferred or paused queue policies until controlled backfill.';

comment on table util.embedding_job_failures is
  'Dead-letter record for embedding jobs removed from pgmq after exceeding retry policy.';

comment on function util.enqueue_pending_embeddings(integer, text, text, text, text) is
  'Enqueues pending embedding jobs in bounded batches; paused policies are not enqueued.';
